apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 7081
      name: monitoring
    - port: 7080
      name: http
      # targetPort: 80
    # - protocol: TCP
    #   port: 443
    #   # targetPort: 443
    #   name: https
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      run: nginx
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
        app: nginx
        tier: backend
    spec:
      containers:
      - name: nginx
        image: bphun/k8-auto-scaling:nginx
        ports:
        - containerPort: 7081
          name: monitoring
        - containerPort: 7080
          name: http
        # - containerPort: 443
          # name: https