apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: 192.168.1.52
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx.nginx
            port:
              number: 80