apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cum-sum-api-hpa
  namespace: cum-sum-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cum-sum-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: cum_sum_api_requests_per_second
      target:
        type: AverageValue
        averageValue: 3k