apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: transaction-api-hpa
  namespace: transaction-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transaction-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: transaction_api_queries_per_second
      target:
        type: AverageValue
        averageValue: 3k