apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels: 
    name: nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: cum-sum-api
  labels: 
    name: cum-sum-api
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels: 
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: cadvisor
  labels: 
    name: cadvisor
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app: metallb
---
apiVersion: v1
kind: Namespace
metadata:
  name: transaction-api
  labels:
    app: transaction-api
---
apiVersion: v1
kind: Namespace
metadata:
  name: transaction-db
  labels:
    app: transaction-db