global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'api_gunicorn'
    static_configs:
      - targets: ['localhost:9091']
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['localhost:9093']

  # - job_name: 'api-service'
  #   metrics_path: '/metrics'
  #   scrape_interval: 5s

  #   kubernetes_sd_configs:
  #   - role: endpoints
  #     namespaces:
  #       names:
  #       - default

  #   relabel_configs:
  #   - source_labels: [__meta_kubernetes_service_label_app]
  #     separator: ;
  #     regex: api-service
  #     replacement: $1
  #     action: keep
  #   - source_labels: [__meta_kubernetes_endpoint_port_name]
  #     separator: ;
  #     regex: http
  #     replacement: $1
  #     action: keep
  #   - source_labels: [__meta_kubernetes_namespace]
  #     separator: ;
  #     regex: (.*)
  #     target_label: namespace
  #     replacement: $1
  #     action: replace
  #   - source_labels: [__meta_kubernetes_pod_name]
  #     separator: ;
  #     regex: (.*)
  #     target_label: pod
  #     replacement: $1
  #     action: replace
  #   - source_labels: [__meta_kubernetes_service_name]
  #     separator: ;
  #     regex: (.*)
  #     target_label: service
  #     replacement: $1
  #     action: replace
    

