global:
  scrape_interval:     1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    metrics_path: /prometheus/metrics
    # static_configs:
    #   - targets: ['localhost:9090']
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - monitoring
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_app]
      separator: ;
      regex: prometheus
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: prometheus
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      target_label: namespace
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_pod_name]
      separator: ;
      regex: (.*)
      target_label: pod
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: (.*)
      target_label: service
      replacement: $1
      action: replace
  - job_name: 'transaction-api'
    scrape_interval: 1s
    # metrics_path: /metrics
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - transaction-api
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_app]
      separator: ;
      regex: transaction-api
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: prometheus
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      target_label: namespace
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_pod_name]
      separator: ;
      regex: (.*)
      target_label: pod
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: (.*)
      target_label: service
      replacement: $1
      action: replace
  - job_name: 'cum-sum-api'
    scrape_interval: 1s
    metrics_path: /statsd/metrics
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - cum-sum-api
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_app]
      separator: ;
      regex: cum-sum-api
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: statsd
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      target_label: namespace
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_pod_name]
      separator: ;
      regex: (.*)
      target_label: pod
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: (.*)
      target_label: service
      replacement: $1
      action: replace
  - job_name: 'mongodb'
    scrape_interval: 1s
    metrics_path: /metrics
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - transaction-db
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_app]
      separator: ;
      regex: transaction-db
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: prometheus
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      target_label: namespace
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_pod_name]
      separator: ;
      regex: (.*)
      target_label: pod
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: (.*)
      target_label: service
      replacement: $1
      action: replace
  - job_name: 'nginx-exporter'
    scrape_interval: 1s
    # static_configs:
    #   - targets: ['localhost:9093']
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - nginx
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_app]
      separator: ;
      regex: nginx
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: nginx-exporter
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      target_label: namespace
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_pod_name]
      separator: ;
      regex: (.*)
      target_label: pod
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: (.*)
      target_label: service
      replacement: $1
      action: replace
  - job_name: 'node-exporter'
    scrape_interval: 1s
    # static_configs:
    #   - targets: ['192.168.49.2:9100']
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
          - monitoring
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_name]
      separator: '/'
      target_label: job
    - source_labels: [__meta_kubernetes_pod_node_name]
      target_label: node
  - job_name: cadvisor
    scrape_interval: 1s
    metrics_path: /cadvisor/metrics
    tls_config:
      insecure_skip_verify: true
    # static_configs:
    #   - targets: [ '192.168.49.2:8080' ]
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
          - cadvisor
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_name]
      separator: '/'
      target_label: job
    - source_labels: [__meta_kubernetes_pod_node_name]
      target_label: node
  # - job_name: 'api-service'
  #   metrics_path: '/metrics'
  #   scrape_interval: 1s

  #   kubernetes_sd_configs:
  #   - role: endpoints
  #     namespaces:
  #       names:
  #       - default

  #   relabel_configs:
  #   - source_labels: [__meta_kubernetes_service_label_app]
  #     separator: ;
  #     regex: api-service
  #     replacement: $1
  #     action: keep
  #   - source_labels: [__meta_kubernetes_endpoint_port_name]
  #     separator: ;
  #     regex: http
  #     replacement: $1
  #     action: keep
  #   - source_labels: [__meta_kubernetes_namespace]
  #     separator: ;
  #     regex: (.*)
  #     target_label: namespace
  #     replacement: $1
  #     action: replace
  #   - source_labels: [__meta_kubernetes_pod_name]
  #     separator: ;
  #     regex: (.*)
  #     target_label: pod
  #     replacement: $1
  #     action: replace
  #   - source_labels: [__meta_kubernetes_service_name]
  #     separator: ;
  #     regex: (.*)
  #     target_label: service
  #     replacement: $1
  #     action: replace
    

