apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app: jaeger-collector
    jaeger-infra: collector-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jaeger-collector
  template:
    metadata:
      labels:
        app: jaeger-collector
        jaeger-infra: collector-pod
    spec:
      containers:
      - image: jaegertracing/jaeger-collector:1.22.0
        name: jaeger-collector
        # args: ["--config-file=/conf/collector.yaml", "--es-archive.timeout=30s", "--log-level=debug"]
        args: ["--config-file=/conf/collector.yaml", "--sampling.strategies-file=/conf/sampling-strategy.json", "--es-archive.timeout=30s", "--log-level=debug"]
        ports:
        - containerPort: 14267
          protocol: TCP
        - containerPort: 14250
          protocol: TCP
        - containerPort: 14268
          protocol: TCP
        - containerPort: 9411
          protocol: TCP
        readinessProbe:
          httpGet:
            path: "/"
            port: 14269
        volumeMounts:
        - name: jaeger-configuration-volume
          mountPath: /conf
        env:
        - name: SPAN_STORAGE_TYPE
          valueFrom:
            configMapKeyRef:
              name: jaeger-configuration
              key: span-storage-type
      volumes:
        - configMap:
            name: jaeger-configuration
            items:
              - key: collector
                path: collector.yaml
              - key: sampling-strategy
                path: sampling-strategy.json
          name: jaeger-configuration-volume
        # - configMap:
        #     name: jaeger-configuration
        #     items:
        #       - key: sampling-strategy
        #         path: sampling-strategy.json
        #   name: jaeger-sampling-strategy
    # resources:
    #   requests:
    #     memory: 300M
    #     cpu: 250m
    #   limits:
    #     memory: 300M
    #     cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app: jaeger-collector
    jaeger-infra: collector-service
spec:
  ports:
  - name: jaeger-collector-tchannel
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: jaeger-collector
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: grpc
    port: 14250
    protocol: TCP
    targetPort: 14250
  selector:
    jaeger-infra: collector-pod
  type: ClusterIP