{
 "title": "Cum Sum API",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(api_request_duration_count, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Percentage of 2xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_code{status=~\"2..\"}) / sum(api_gunicorn_requests) * 100",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "Percentage of 3xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_code{status=~\"3..\"}) / sum(api_gunicorn_requests) * 100",
     "legendFormat": "3XX"
    }
   ]
  },
  {
   "title": "Percentage of 4xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_code{status=~\"4..\"}) / sum(api_gunicorn_requests) * 100",
     "legendFormat": "4XX"
    }
   ]
  },
  {
   "title": "Percentage of 5xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_code{status=~\"5..\"}) / sum(api_gunicorn_requests) * 100",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Logged critical",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "api_gunicorn_requests_log_critical"
    }
   ]
  },
  {
   "title": "Logged exception",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "api_gunicorn_requests_log_exception"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(api_request_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(api_request_duration_sum / api_request_duration_count) * 1000"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "api_request_duration{quantile=\"0.5\"}",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "api_request_duration{quantile=\"0.9\"}",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "api_request_duration{quantile=\"0.99\"}",
     "legendFormat": "99th percentile"
    }
   ]
  }
 ]
}