{
 "title": "Go gRPC1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(go_memstats_alloc_bytes,job)"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "le",
    "query": "\"0.1\",\"0.15\",\"0.25\",\"0.3\",\"0.5\",\"1\""
   },
   {
    "name": "grpc_service",
    "query": "label_values(grpc_server_handled_total,grpc_service) "
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{service=\"transacion-api\"}"
    }
   ]
  },
  {
   "title": "Global Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code=\"OK\"}[$interval])) + \nsum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code=\"NotFound\"}[$interval])) + \nsum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code=\"PermissionDenied\"}[$interval])) + \nsum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code=\"InvalidArgument\"}[$interval])))\n/ \nsum(rate(grpc_server_started_total{grpc_type=\"unary\"}[$interval]))"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{grpc_service=~\"$grpc_service\"}[$interval]))"
    }
   ]
  },
  {
   "title": "gRPC request code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_service=~\"$grpc_service\",grpc_type=\"unary\"}[$interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_service)",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Average handling time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(grpc_server_handling_seconds_sum{grpc_service=~\"$grpc_service\",grpc_type=\"unary\"}[$interval])) by (grpc_service) * 1000",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  { "title": "$grpc_service gRPC requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "grpc_service" },
  {
   "title": "Request error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Request error percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "99%-tile latency of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Percentage of slow queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{le=\"$le\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n) * 100.0",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  }
 ]
}