{
 "title": "MongoDB",
 "description": "Note for a official Grafana MongoDB plugin, please view:\nhttps://grafana.com/grafana/plugins/grafana-mongodb-datasource\n\nThis is a MongoDB Prometheus Exporter Dashboard. \nWorks well with https://github.com/dcu/mongodb_exporter\n\nIf you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(mongodb_ss_uptime, pod)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Query Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_document{pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_queryExecutor_collectionScans_total{pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Replica Set Metrics for $env",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "env",
   "collapsed": true,
   "panels": [
    {
     "title": "Member Health",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_replset_number_of_members{instance=~\"$env\"}",
       "legendFormat": "# members"
      },
      {
       "expr": "sum(mongodb_replset_member_health{instance=~\"$env\"})",
       "legendFormat": "healthy members"
      }
     ]
    },
    {
     "title": "Member State",
     "type": "graph",
     "description": "See which node is currently acting as the primary, secondary, ...",
     "gridPos": { "h": 6, "w": 12, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_replset_member_state{instance=~\"$env\"}",
       "legendFormat": "{{state}} - {{name}}"
      }
     ]
    },
    {
     "title": "Replica Query Operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_op_counters_repl_total{instance=~\"$env\"}[$interval])",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  { "title": "Health metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_ss_uptime{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_ss_connections{pod=~\"$pod\", conn_type=\"available\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_ss_connections{pod=~\"$pod\",conn_type=\"current\"}"
    }
   ]
  },
  {
   "title": "Resource Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oplog Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_replset_oplog_size_bytes{instance=~\"$env\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "deckbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "mongodb_sys_memory_Active_kb{pod=~\"$pod\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "mongodb_sys_memory_Cached_kb{pod=~\"$pod\"}",
       "legendFormat": "Cached"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_ss_network_bytesIn{pod=~\"$pod\"}[$interval])",
       "legendFormat": "In"
      },
      {
       "expr": "rate(mongodb_ss_network_bytesOut{pod=~\"$pod\"}[$interval])",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oplog Lag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_replset_oplog_head_timestamp[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk IO Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_io_time_ms{instance=~\"shr.*\"}[5m])/1000 or irate(node_disk_io_time_ms{instance=~\"shr.*\"}[5m])/1000)",
       "legendFormat": "{{device}} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Reads Completed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed{instance=~\"shr.*\"}[5m])",
       "legendFormat": "{{device}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Writes Completed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_writes_completed{instance=~\"shr.*\"}[5m])",
       "legendFormat": "{{device}} - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}