apiVersion: v1
kind: Service
metadata:
  namespace: cum-sum-api
  name: cum-sum-api
  labels:
    app: cum-sum-api
spec:
  selector:
    app: cum-sum-api
  ports:
  - port: 5000
    name: http
  - port: 9091
    name: statsd
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cum-sum-api
  name: cum-sum-api
spec:
  selector:
    matchLabels:
      app: cum-sum-api
      run: cum-sum-api
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: cum-sum-api
        app: cum-sum-api
        tier: backend
    spec:
      volumes:
        - name: cum-sum-api-pv-volume
          persistentVolumeClaim:
            claimName: cum-sum-api-pv-claim
    spec:
      containers:
      - name: cum-sum-api
        image: public.ecr.aws/h6v8s1y1/k8s-autoscaling:cum-sum-api
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     cpu: "4000m"
        #     memory: "5000Mi"
        #   limits:
        #     cpu: "7000m"
        #     memory: "14000Mi"
        # volumeMounts:
        # - name: cum-sum-api-service-pv-volume
        #   mountPath: /etc/api-logs/
        ports:
        - containerPort: 5001
      - name: statsd
        image: public.ecr.aws/h6v8s1y1/k8s-autoscaling:statsd
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        - containerPort: 9125
          protocol: UDP
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   namespace: cum-sum-api
#   name: cum-sum-api-service
# spec:
#   containers:
#       - name: cum-sum-api-service
#         image: public.ecr.aws/h6v8s1y1/k8s-autoscaling:cum-sum-api
#         imagePullPolicy: Always
#         resources:
#           requests:
#             cpu: "4000m"
#             memory: "5000Mi"
#           limits:
#             cpu: "7000m"
#             memory: "14000Mi"
#         # volumeMounts:
#         # - name: cum-sum-api-service-pv-volume
#         #   mountPath: /etc/api-logs/
#         ports:
#         - containerPort: 5000
#       - name: statsd
#         image: public.ecr.aws/h6v8s1y1/k8s-autoscaling:statsd
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 9091
#         - containerPort: 9125
#           protocol: UDP
#         env:
#         - name: FLASK_ENV
#           value: "production"