apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
    - seriesQuery: 'api_gunicorn_request_duration_sum'
      name:
        matches: 'request_duration'
        as: 'request_duration'
      metricsQuery: '(api_gunicorn_request_duration_sum{<<.LabelMatchers>>} by (<<.GroupBy>>) / api_gunicorn_request_duration_count{<<.LabelMatchers>>}) by (<<.GroupBy>>)'