apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  # namespace: monitoring
data:
  config.yaml: |
    rules:
      - seriesQuery: 'api_gunicorn_request_duration_sum'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: ""
          as: "request_duration"
        metricsQuery: (api_gunicorn_request_duration_sum / api_gunicorn_request_duration_count)