# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: adapter-config
#   # namespace: monitoring
# data:
#   config.yaml: |
#     rules:
#       - seriesQuery: 'api_gunicorn_requests'
#         resources:
#           overrides:
#             namespace:
#               resource: namespace
#             pod:
#               resource: pod
#         name:
#           matches: ""
#           as: "requests_per_second"
#         metricsQuery: rate(api_gunicorn_requests[1m])
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  # namespace: monitoring
data:
  config.yaml: |
    rules:
      - seriesQuery: 'api_request_duration_count'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: ""
          as: "requests_per_second"
        metricsQuery: rate(api_request_duration_count[1m])