apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: api
  name: api-service-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Mi
---      
apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-service-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 80Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/k8sAutoScalingTestVolumes/apiService"