apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-elasticsearch-elasticsearch-master-0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/bphan/k8sAutoScalingTest/volumes/elasticsearch"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   namespace: monitoring
#   name: data-elasticsearch-elasticsearch-master-0
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi