// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: TransactionAPI/TransactionAPI.proto

package TransactionAPI

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InArr     []int32 `protobuf:"zigzag32,1,rep,packed,name=inArr,proto3" json:"inArr,omitempty"`
	OutArr    []int32 `protobuf:"zigzag32,2,rep,packed,name=outArr,proto3" json:"outArr,omitempty"`
	StartTime uint32  `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	ExecTime  int64   `protobuf:"varint,4,opt,name=execTime,proto3" json:"execTime,omitempty"`
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TransactionAPI_TransactionAPI_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TransactionAPI_TransactionAPI_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_TransactionAPI_TransactionAPI_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetInArr() []int32 {
	if x != nil {
		return x.InArr
	}
	return nil
}

func (x *TransactionRequest) GetOutArr() []int32 {
	if x != nil {
		return x.OutArr
	}
	return nil
}

func (x *TransactionRequest) GetStartTime() uint32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TransactionRequest) GetExecTime() int64 {
	if x != nil {
		return x.ExecTime
	}
	return 0
}

type TransactionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TransactionReply) Reset() {
	*x = TransactionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TransactionAPI_TransactionAPI_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReply) ProtoMessage() {}

func (x *TransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_TransactionAPI_TransactionAPI_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReply.ProtoReflect.Descriptor instead.
func (*TransactionReply) Descriptor() ([]byte, []int) {
	return file_TransactionAPI_TransactionAPI_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_TransactionAPI_TransactionAPI_proto protoreflect.FileDescriptor

var file_TransactionAPI_TransactionAPI_proto_rawDesc = []byte{
	0x0a, 0x23, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x50, 0x49,
	0x2f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x50, 0x49, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x50, 0x49, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x05,
	0x69, 0x6e, 0x41, 0x72, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x11, 0x42, 0x02, 0x10, 0x01, 0x52,
	0x05, 0x69, 0x6e, 0x41, 0x72, 0x72, 0x12, 0x1a, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x41, 0x72, 0x72,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x11, 0x42, 0x02, 0x10, 0x01, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x41,
	0x72, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x63, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x65, 0x78, 0x65, 0x63, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x10,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x6b, 0x0a, 0x0e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x50, 0x49, 0x12, 0x59, 0x0a, 0x0f,
	0x53, 0x61, 0x76, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x22, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x50, 0x49,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x50, 0x49, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x70, 0x68, 0x75, 0x6e, 0x2f, 0x4b, 0x75, 0x62, 0x65,
	0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e,
	0x67, 0x2f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x50, 0x49,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TransactionAPI_TransactionAPI_proto_rawDescOnce sync.Once
	file_TransactionAPI_TransactionAPI_proto_rawDescData = file_TransactionAPI_TransactionAPI_proto_rawDesc
)

func file_TransactionAPI_TransactionAPI_proto_rawDescGZIP() []byte {
	file_TransactionAPI_TransactionAPI_proto_rawDescOnce.Do(func() {
		file_TransactionAPI_TransactionAPI_proto_rawDescData = protoimpl.X.CompressGZIP(file_TransactionAPI_TransactionAPI_proto_rawDescData)
	})
	return file_TransactionAPI_TransactionAPI_proto_rawDescData
}

var file_TransactionAPI_TransactionAPI_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_TransactionAPI_TransactionAPI_proto_goTypes = []interface{}{
	(*TransactionRequest)(nil), // 0: TransactionAPI.TransactionRequest
	(*TransactionReply)(nil),   // 1: TransactionAPI.TransactionReply
}
var file_TransactionAPI_TransactionAPI_proto_depIdxs = []int32{
	0, // 0: TransactionAPI.TransactionAPI.SaveTransaction:input_type -> TransactionAPI.TransactionRequest
	1, // 1: TransactionAPI.TransactionAPI.SaveTransaction:output_type -> TransactionAPI.TransactionReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TransactionAPI_TransactionAPI_proto_init() }
func file_TransactionAPI_TransactionAPI_proto_init() {
	if File_TransactionAPI_TransactionAPI_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TransactionAPI_TransactionAPI_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TransactionAPI_TransactionAPI_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TransactionAPI_TransactionAPI_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TransactionAPI_TransactionAPI_proto_goTypes,
		DependencyIndexes: file_TransactionAPI_TransactionAPI_proto_depIdxs,
		MessageInfos:      file_TransactionAPI_TransactionAPI_proto_msgTypes,
	}.Build()
	File_TransactionAPI_TransactionAPI_proto = out.File
	file_TransactionAPI_TransactionAPI_proto_rawDesc = nil
	file_TransactionAPI_TransactionAPI_proto_goTypes = nil
	file_TransactionAPI_TransactionAPI_proto_depIdxs = nil
}
