// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package TransactionAPI

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactionAPIClient is the client API for TransactionAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionAPIClient interface {
	SaveTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error)
}

type transactionAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionAPIClient(cc grpc.ClientConnInterface) TransactionAPIClient {
	return &transactionAPIClient{cc}
}

func (c *transactionAPIClient) SaveTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, "/TransactionAPI.TransactionAPI/SaveTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionAPIServer is the server API for TransactionAPI service.
// All implementations must embed UnimplementedTransactionAPIServer
// for forward compatibility
type TransactionAPIServer interface {
	SaveTransaction(context.Context, *TransactionRequest) (*TransactionReply, error)
	mustEmbedUnimplementedTransactionAPIServer()
}

// UnimplementedTransactionAPIServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionAPIServer struct {
}

func (UnimplementedTransactionAPIServer) SaveTransaction(context.Context, *TransactionRequest) (*TransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTransaction not implemented")
}
func (UnimplementedTransactionAPIServer) mustEmbedUnimplementedTransactionAPIServer() {}

// UnsafeTransactionAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionAPIServer will
// result in compilation errors.
type UnsafeTransactionAPIServer interface {
	mustEmbedUnimplementedTransactionAPIServer()
}

func RegisterTransactionAPIServer(s grpc.ServiceRegistrar, srv TransactionAPIServer) {
	s.RegisterService(&TransactionAPI_ServiceDesc, srv)
}

func _TransactionAPI_SaveTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionAPIServer).SaveTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TransactionAPI.TransactionAPI/SaveTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionAPIServer).SaveTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionAPI_ServiceDesc is the grpc.ServiceDesc for TransactionAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TransactionAPI.TransactionAPI",
	HandlerType: (*TransactionAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveTransaction",
			Handler:    _TransactionAPI_SaveTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TransactionAPI/TransactionAPI.proto",
}
